# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"filter_post": "01_fb_scraper.ipynb",
         "extract_comments": "01_fb_scraper.ipynb",
         "FbScraper": "01_fb_scraper.ipynb"}

modules = ["fb_scraper.py"]

doc_url = "https://MJPansa.github.io/scrapinghub/"

git_url = "https://github.com/MJPansa/scrapinghub/tree/master/"

def custom_doc_links(name): return None
